name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/workflows/docs.yaml'
  pull_request:
    branches: [master]
    paths-ignore:
      - '.github/workflows/docs.yaml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-15
          - macos-latest
          - windows-latest
        bazel: ['7.x', '8.x']
        include:
          - os: ubuntu-latest
            name: Linux x86_64
          - os: ubuntu-24.04-arm
            name: Linux ARM64
          - os: macos-15
            name: macOS x86_64
          - os: macos-latest
            name: macOS ARM64
          - os: windows-latest
            name: Windows x86_64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }} (Bazel ${{ matrix.bazel }})
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel }}
      MSYS_NO_PATHCONV: 1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
          bazelisk-version: 1.x
      - name: Run unit tests
        run: bazel test //test/... --verbose_failures --test_output=all
      - name: Run examples
        # TODO: switch to //... since we don't want to miss any
        run: cd examples && bazel test //basic:all //blas:all //omp:all --verbose_failures --test_output=all
      - name: Build wasm32 targets
        run: cd examples && bazel build //wasm:hello_wasm //wasm:full_wasm //wasm:omp_hello_wasm --verbose_failures
      - name: Run wasm32 tests
        run: |
          node examples/bazel-bin/wasm/hello_cc.js
          node examples/bazel-bin/wasm/full.js
          node examples/bazel-bin/wasm/omp_hello_cc.js

  docs:
    runs-on: ubuntu-latest
    env:
      USE_BAZEL_VERSION: 8.x
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
          bazelisk-version: 1.x
      - name: Generate API docs
        run: |
          bazel build //docs:rules_doc
          cp bazel-bin/docs/rules.md docs/reference/api.md
      - name: Build docs
        run: cd docs && npm install && npm run docs:build