name: Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  id-token: write
  attestations: write
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.4.0
    with:
      prerelease: false
      release_files: rules_fortran-*.tar.gz
      tag_name: ${{ github.ref_name }}
